import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import { ThemeProvider } from '@mui/material'
import { LightTheme } from '@/shared/themes/light'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cadastros',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <ThemeProvider theme={LightTheme}>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  )
}
