import MenuLateral from '@/shared/components/MenuLateral'
import type { Metadata } from 'next'
import { 
  DrawerProvider 
} from '@/shared/contexts/Menu/DrawerContext'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function DasboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <DrawerProvider>
        <MenuLateral>
          {children}  
        </MenuLateral>
      </DrawerProvider>
    </div>
  )
}
