import MenuLateral from '@/shared/components/MenuLateral'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function DasboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <MenuLateral>
        {children}  
      </MenuLateral>
    </div>
  )
}
